# the config of mast
use_seg: false
resize: 0
type: 32
encoder_path: 'trained_models/MAST_models/no_connection_models/vgg_r51.pth'
decoder_r11_path: 'trained_models/MAST_models/no_connection_models/dec_r11.pth'
decoder_r21_path: 'trained_models/MAST_models/no_connection_models/dec_r21.pth'
decoder_r31_path: 'trained_models/MAST_models/no_connection_models/dec_r31.pth'
decoder_r41_path: 'trained_models/MAST_models/no_connection_models/dec_r41.pth'
decoder_r51_path: 'trained_models/MAST_models/no_connection_models/dec_r51.pth'
layers: 'r41,r31,r21,r11'
orth_constraint: false
post_smoothing: false
fast: false
gpu: 0
device: ''
max_use_num: -1
soft_lambda: 0.05
k_cross: 5
patch_size: 1
style_weight: 0.6
reduce_dim_type: 'avg_pool'
dist_type: 'cosine'
dim_thresh: 128

